=== mxc/selenium-demo-2018-03/xml/src/main/resources/product.xsd
<?xm	l version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/product" xmlns:tns="http://www.example.org/product" elementFormDefault="qualified">
<element name="productlist">
	<complexType>
		<sequence>
			<element ref="tns:product" minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
</element>
<element name="product">
	<complexType>
		<sequence>
			<element name="sku" type="string" minOccurs="1" />
			<element name="description" type="string" />
			<element name="price" type="double" minOccurs="1" />
			<element name="manufacturer" type="string" />
		</sequence>
		<attribute ref="tns:activefrom" />
	</complexType>
</element>
<complexType name="manufacturer">
	<sequence>
	   <element name="name" type="string" />
	</sequence>
</complexType>
<attribute name="activefrom" type="date" />
</schema>

=== mxc/selenium-demo-2018-03/xml/src/main/resources/productlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:productlist xmlns:tns="http://www.example.org/product" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/product target/classes/product.xsd "> 
<tns:product>
  <tns:sku>tns:sku</tns:sku>
  <tns:description>tns:description</tns:description>
  <tns:price>0.0</tns:price>
  <tns:manufacturer>tns:manufacturer</tns:manufacturer>
</tns:product>
<tns:product>
  <tns:sku>tns:sku</tns:sku>
  <tns:description>tns:description</tns:description>
  <tns:price>100</tns:price>
  <tns:manufacturer>ABC Co</tns:manufacturer>
</tns:product>
</tns:productlist>
