=== mxc/selenium-demo-2018-03/XmlDemo/src/main/resources/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/books" 
xmlns:tns="http://www.example.org/books" 
elementFormDefault="qualified">
<element name="books">
 <complexType>
 	<sequence>
 		<element name="book" maxOccurs="unbounded" 
 		minOccurs="1" type="tns:bookType" />
		<element name="author" type="tns:authorType" 
		maxOccurs="unbounded" />
 	</sequence>
 	<attribute name="lastUpdated" type="date" use="required" />
 </complexType>
</element>

<complexType name="authorType">
<sequence>
	<element name="name" type="string" />
	<element name="work" type="IDREFS" />
</sequence>
</complexType>

<complexType name="bookType">
<sequence>
	<element name="title" type="string" />
	<element name="price" type="double" minOccurs="0" />
	<element name="author" type="string" maxOccurs="unbounded" />
</sequence>
<attribute name="isbn" type="string"/>
<attribute name="myid"  type="ID" use="required"/>
</complexType>

</schema>

=== mxc/selenium-demo-2018-03/XmlDemo/src/main/resources/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<books lastUpdated="2018-03-07" xmlns="http://www.example.org/books" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.example.org/books books.xsd ">
	<book myid="b1">
	  	<title>Book1</title>
	  	<price>100</price>
	  	<author>Bob</author>
	  	<author>Sue</author>
	</book>
	<book myid="b2">
		<title>Book2</title>
		<price>100.00</price>
		<author>Arnold</author>
	</book>
	<author>
		<name>Bob</name>
		<work>b1</work>
	</author>
</books>
